version: '3.1'
services:
  cassandra:
    image: cassandra
    container_name: cassandra
    restart: always
    ports:
      - "9042:9042"
    volumes:
      - ~/apps/cassandra:/var/lib/cassandra
    environment:
      CASSANDRA_CLUSTER_NAME: "watt4cast"
      CASSANDRA_DC: "datacenter1"
  mongo:
    image: mongo:6.0
    container_name: mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - ./data/db:/data/db
    environment:
     # MONGO_INITDB_ROOT_USERNAME: root
      #MONGO_INITDB_ROOT_PASSWORD: root
      MONGO_INITDB_DATABASE: db

  backend:
    build: .
    ports:
      - "3000:3000"
    restart: always
    env_file: .env.docker
    environment:
      - DB_URI=mongodb://mongo:27017/db
      - CASSANDRA_CONTACT_POINTS=cassandra
    depends_on: [ cassandra, mongo ]
volumes:
  mongo:
  cassandra: