name: Nest CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 16

      - run: npm ci

      - name: Test
        run: npm run test
        env:
          DB_URI: ${{ secrets.DB_URI }}
          WEATHER_API_KEY: ${{ secrets.WEATHER_API_KEY }}
          NODE_ENV: test
          URL_PREFIX: /api

      - run: npm run build

      - name: Install Railway
        run: npm i -g @railway/cli

      - name: Deploy
        run: railway up
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}

