name: Nest CI
env:
  DB_URI: ${{ secrets.DB_URI }}
  WEATHER_API_KEY: ${{ secrets.WEATHER_API_KEY }}
  NODE_ENV: test
  URL_PREFIX: /api

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 16
      - run: npm ci
      - run: npm run test:full
      - run: npm run build

      - name: Install Railway
        run: npm i -g @railway/cli

      - name: Deploy
        run: railway up
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}

